apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        {{ if .Values.managedIdentity.enabled }}
        aadpodidbinding: {{ .Values.managedIdentity.name }}
        {{ end }}
    spec:
      containers:
      - name: worker
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        {{ if (.Values.healthChecks).readinessRoute }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthChecks.readinessRoute }}
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
        {{ end }}
        imagePullPolicy: IfNotPresent
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: worker
      nodeSelector:
        kubernetes.io/os: linux
      {{ if .Values.useAcrSecret }}
      imagePullSecrets:
      - name: acr-secret
      {{ end }}
