apiVersion: v1
kind: Service
metadata:
  name: azurite
  namespace: blog
spec:
  type: NodePort
  ports:
  - port: 10000
    nodePort: 32001
    targetPort: 10000
  selector:
    app: azurite
