apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: 'true'
        - name: SA_PASSWORD
          value: 'localdevpassword#123'