version: '3'

services:
 web:
   build:
     context: .
     dockerfile: DanClarkeBlog.Web/Dockerfile
   ports:
     - 12311:80
   links:
     - rabbitmq
     - postgres
   volumes:
     - ./DanClarkeBlog.Core:/src/DanClarkeBlog.Core
     - ./DanClarkeBlog.Web:/src/DanClarkeBlog.Web
   restart: always
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - Blog__BlogSqlConnectionString=Host=postgres;Database=blog;Port=5432;Username=blog;password=password1
     - Blog__AzureStorageConnectionString
     - Blog__DisqusDomainName
     - Blog__SlackNotificationUri
     - Blog__SiteHomeUri
     - Blog__ProfilePicUri
     - Blog__GoogleAnalyticsTracking
     - Blog__RabbitMQServer=rabbitmq
     - Blog__RabbitMQUser=guest
     - Blog__RabbitMQPass=guest
     - Blog__DropboxAccessToken
     - Blog__DropboxAppSecret
     - Blog__MaxResizedImageSize
