apiVersion: v1
kind: ConfigMap
metadata:
  name: web
  namespace: blog
data:
  ASPNETCORE_ENVIRONMENT: 'Production'
  Blog__AzureSearchIndexName: 'azuresql-index-sortable'
  Blog__AzureSearchInstanceName: {{ .Values.config.azureSearchIndexName | quote }}
  Blog__BaseImageUri: {{ .Values.config.baseImageUri | quote }}
  Blog__DisqusDomainName: {{ .Values.config.disqusDomainName | quote }}
  Blog__GoogleAnalyticsTrackingId: {{ .Values.config.googleAnalyticsTrackingId | quote }}
  Blog__ProfilePicUri: {{ .Values.config.profilePicUri | quote }}
  Blog__SiteHomeUri: {{ .Values.config.siteHomeUri | quote }}
