apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: GET_HOSTS_FROM
          value: dns
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
          - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: blog
spec:
  type: ClusterIP
  # type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres
