apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6-management
        ports:
        - containerPort: 5672
        envFrom:
        - configMapRef:
            name: rabbitmq-config
        resources:
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: blog
spec:
  type: ClusterIP
  ports:
  - port: 5672
  selector:
    name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-manage
  namespace: blog
spec:
  # type: ClusterIP
  type: LoadBalancer
  ports:
  - port: 15672
  selector:
    name: rabbitmq
