apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seq
  namespace: blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        env:
        - name: ACCEPT_EULA
          value: 'Y'
        # envFrom:
        # - configMapRef:
        #     name: seq-config
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: blog
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: seq
