apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tasks
  namespace: blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tasks
    spec:
      containers:
      - name: tasks
        image: everstack.azurecr.io/blog-tasks:2.0.6
        envFrom:
        - configMapRef:
            name: tasks-config
