apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-prod
  namespace: blog
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: web
        env: prod
    spec:
      containers:
      - name: web
        image: everstack.azurecr.io/blog:2.0.11
        envFrom:
        - configMapRef:
            name: web-config
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: blog
  labels:
    name: web
    env: prod
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    name: web
    env: prod
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: web
#   namespace: monitoring
#   labels:
#     prometheus: kube-prometheus
# spec:
#   selector:
#     matchLabels:
#       name: web
#       env: prod
#   namespaceSelector:
#     matchNames:
#     - blog
#   endpoints:
#   - port: web
#     interval: 30s
