apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-prod
  namespace: blog
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: web
        env: prod
    spec:
      containers:
      - name: web
        image: eu.gcr.io/composed-region-200213/blog:2.0.2
        envFrom:
        - configMapRef:
            name: web-config
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: blog
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: web
    env: prod
